### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jwg4** [moygit/exact_cover_np#4]
Hi Moy,

Thanks for this code!

I've made a few updates to get it working with Python 3. (They break Python 2 compatibility but I figured that was ok since it's end-of-lifed. Making it work with both shouldn't be too much harder.) You can see what I've done at https://github.com/jwg4/exact_cover_np/pull/1

I just wondered whether you would care to merge these in. If you're not bothered, I might submit to pypi under a slightly different name? Let me know what you think.

**Comment by moygit** [comment]
@jwg4 thanks! Can you give me a pull request, please?
